// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecraftSeeds.data;

namespace MinecraftSeeds.Migrations
{
    [DbContext(typeof(MineCraftSeedContext))]
    partial class MineCraftSeedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinecraftSeeds.data.seed", b =>
                {
                    b.Property<int>("SeedID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("SeedText");

                    b.Property<string>("SeedValue");

                    b.Property<string>("Title");

                    b.Property<string>("version");

                    b.HasKey("SeedID");

                    b.ToTable("Seeds");
                });
#pragma warning restore 612, 618
        }
    }
}
